config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "shows#index"
  resources :users
  resources :shows, only: [:index, :show] do
    resources :reviews, only: [:new, :edit, :update]
    resources :favorites, only: [:new, :create]
  end

  resources :favorites, only: [:destroy]
  resources :reviews, only: [:show, :destroy] do
    resources :votes
  end

  namespace :api do
    namespace :v1 do
      resources :shows, only: [:show]
      resources :reviews, only: [:create, :update]
    end
  end
end

app/models/show.rb
class Show < ApplicationRecord
  validates :title, presence: true

  validates :average_rating, numericality: true, allow_blank: true
  validates :average_rating, inclusion: { in: 1..5 }, allow_blank: true

  has_many :favorites
  has_many :users, through: :favorites
  has_many :reviews

  def self.search(search)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.average_rating_calc(show)
    rating_total = 0
    if !show.nil? && !show.reviews.nil?
      show.reviews.each do |review|
        rating_total += review.rating
      end
      average_rating = rating_total / show.reviews.count.to_f
      show.average_rating = average_rating
      show.save!
    end
  end
end

app/controllers/api/v1/shows_controller.rb
class Api::V1::ShowsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def show
    @reviews = []
    Show.find(params[:id]).reviews.each do |review|
      review_to_send = {}
      review_to_send[:id] = review.id
      review_to_send[:title] = review.title
      review_to_send[:description] = review.description
      review_to_send[:rating] = review.rating
      review_to_send[:total_votes] = review.total_votes
      @reviews << review_to_send
    end
    render json: { reviews: @reviews }
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def show
    @show = Show.find(params[:id])
    @reviews = @show.reviews.order("total_votes DESC")
    Show.average_rating_calc(@show)
  end

  def index
    @shows = Show.all
    @shows =
      if params[:search]
        Show.search(params[:search]).order("created_at DESC")
      else
        Show.all.order("created_at ASC")
      end
  end
end

app/views/shows/index.html.erb
<h1 class="index-title">Popular Shows</h1>
<div class="row index-row small-up-2 medium-up-3 large-up-4">
  <% @shows.each do |show| %>
  <div class="column column-block">
    <div class"show-card">
      <div class="overlay-container">
        <%= link_to image_tag(show.image_url), show_path(show), id: "show-link" %>
        <div class="overlay">
          <% if current_user %>
          <% if current_user && current_user.shows.include?(show) %>
          <%= link_to "Remove from Favorites", Favorite.find_by(user_id: current_user, show_id: show), :method => :delete, class: "button alert" %>
          <% else %>
          <%= link_to "Add to Favorites", show_favorites_path(show, current_user), :method => :post, class: "button success" %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if @shows.blank? %>
  <h4>There are no shows containing the term <%= params[:search] %>.</h4>
  <% end %>
  <% end %>
</div>

app/views/shows/show.html.erb
<div>
  <div class="row">
    <div class="small-9 columns">
      <div class="card">
        <h2><%= @show.title %></h2>
        <div class="overlay-container">
          <%= link_to image_tag(@show.image_url), show_path(@show) %>
          <div class="overlay">
            <% if current_user %>
            <% if current_user && current_user.shows.include?(@show) %>
            <%= link_to "Remove from Favorites", Favorite.find_by(user_id: current_user, show_id: @show), :method => :delete, class: "button alert" %>
            <% else %>
            <%= link_to "Add to Favorites", show_favorites_path(@show, current_user), :method => :post, class: "button success" %>
            <% end %>
            <% end %>
          </div>
        </div>
        <div class="card-section">
          <h4>Description</h4>
          <p><%= @show.description %></p>
        </div>
        <div class="card-section">
          <p>Average Rating: <%= @show.average_rating %></p>
        </div>
      </div>
    </div>
    <div class="small-3 columns">
      <div class="card">
        <div class="card-section">
          <h2>Other Users Who Like <%= @show.title%></h2>
        </div>
        <div class="card-divider">
          <ul class="user-list"><% @show.users.each do |user| %>
            <li>
            <%= user.username %>
            <%= link_to image_tag(user.avatar.thumb.url), user_path(user) %></li>
          <% end %></ul>
        </div>
      </div>
    </div>

  </div>

  <div class="review-section row">
    <div id="app"></div>
  </div>

</div>