config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "shows#index"
  resources :users
  resources :shows, only: [:index, :show] do
    resources :reviews, only: [:new, :edit, :update]
    resources :favorites, only: [:new, :create]
  end

  resources :favorites, only: [:destroy]
  resources :reviews, only: [:show, :destroy] do
    resources :votes
  end

  namespace :api do
    namespace :v1 do
      resources :shows, only: [:show]
      resources :reviews, only: [:create, :update]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TV a la Carte</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar-container" data-sticky-container>
      <div class="sticky sticky-topbar" data-sticky data-options="marginTop:0;" style="width:100%">
        <div class="top-bar">
          <div class="top-bar-title">
            <%= link_to root_path do %>
              <%= image_tag("logo_primary.png", class: "menu-icon") %>
            <% end %>
          </div>
          <div class="top-bar-left"></div>
          <div class="top-bar-right">
            <ul class="menu">
              <% if current_user %>
                <li class="menu-text"><%= "#{current_user.username}" %></li>
                <li class="menu-text"><%= link_to "Profile", user_path(current_user) %></li>
                <li class="menu-text"><%= link_to 'Sign out', destroy_user_session_path, method: "delete" %></li>
              <% else %>
                <li><%= link_to 'Create Account', new_user_registration_path, class: "button" %></li>
                <li><%= link_to 'Sign in', new_user_session_path, class: "button" %></li>
              <% end %>
              <% if current_user && current_user.admin? %>
                <li><%= link_to 'User Admin', users_path %></li>
              <% end %>
              <li class="has-form">
                <%= form_tag(shows_path, :method => "get", id: "search-form") do %>
                  <div class="row collapse">
                    <div class="small-8 columns">
                      <%= text_field_tag :search, params[:search], placeholder: "Search Shows"%>
                    </div>
                    <div class="small-4 columns">
                      <%= submit_tag "Search", name: nil, class: "button" %>
                    </div>
                  </div>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <% if notice %>
      <div class="success callout" data-closable><%= notice %>
        <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert callout" data-closable><%= alert %>
        <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <div>
      <%= yield %>
    </div>

  </body>
</html>